language: python

sudo: required
dist: trusty

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-overwrite" -f
      cmake
      curl
      freeglut3-dev
      g++
      gperf
      libbz2-dev
      libegl1-mesa-dev
      libfreetype6-dev
      libgl1-mesa-dri
      libgles2-mesa-dev
      libglib2.0-dev
      libglu1-mesa-dev
      libosmesa6-dev
      libssl-dev
      libxmu-dev
      libxmu6
      python-pip
      python-virtualenv
      xorg-dev
      ant
      expect
      lib32gcc1
      lib32stdc++6
      lib32z1
      openjdk-7-jdk

script:
  - python csibe.py
