language: python

sudo: required
dist: trusty

matrix:
  include:
    # default gcc toolchains
    #   native x86_64
    #   gcc-cortex-m0
    #   gcc-cortex-m4
    - env:
      - OPTS="native gcc-cortex-m0 gcc-cortex-m4"

    # default clang toolchains
    #   native x86_64
    #   clang-cortex-m0
    #   clang-cortex-m4
    - env:
      - CC=clang
      - CXX=clang++
      - OPTS="native clang-cortex-m0 clang-cortex-m4"

      before_script:
      - wget http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
      - tar xf clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
      - export DIR=`pwd`/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin
      - export PATH=$DIR:$PATH
      - sudo update-alternatives --install /usr/bin/clang clang $DIR/clang 100
      - sudo update-alternatives --set clang $DIR/clang
      - sudo update-alternatives --install /usr/bin/clang++ clang++ $DIR/clang++ 100
      - sudo update-alternatives --set clang++ $DIR/clang++
      - sudo ln -s /usr/include/asm-generic /usr/include/asm

install:
  - sudo apt-get install -y
      cmake
      g++
      gcc-arm-none-eabi
      libc6-dev
      libc6-dev-i386
      python
      wget

script:
  - python csibe.py $OPTS
